DWAPlannerROS:
    # Robot Configuration Parameters
    acc_lim_x: 3.0
    acc_lim_y: 0.0
    acc_lim_theta: 2.8
    acc_lim_trans: 3.0
    
    max_vel_trans: 2.6
    min_vel_trans: 0.10

    max_vel_x: 2.6
    min_vel_x: 0.0
    max_vel_y: 0.0
    min_vel_y: 0.0

    max_vel_theta: 1.2
    min_vel_theta: 0.30
    trans_stopped_vel: 0.10
    theta_stopped_vel: 0.10

    # Goal Tolerance Parameters
    yaw_goal_tolerance: 0.35
    xy_goal_tolerance: 0.22
    latch_xy_goal_tolerance: false

    # Forward Simulation Parameters
    sim_time: 1.5
    sim_granularity: 0.025
    angular_sim_granularity: 0.05
    vx_samples: 8
    vy_samples: 0
    vth_samples: 24
    use_dwa: true

    # Trajectory Scoring Parameters
    meter_scoring: true
    path_distance_bias: 0.6
    goal_distance_bias: 0.8
    occdist_scale: 0.005
    forward_point_distance: 0.325
    stop_time_buffer: 0.10
    scaling_speed: 10.0
    max_scaling_factor: 0.0
    publish_cost_grid: false
    global_frame_id: odom
    penalize_negative_x: true

    # Oscillation Prevention Parameters
    oscillation_reset_dist: 0.10

    # Global Plan Parameters
    prune_plan: true
