TebLocalPlannerROS:
  odom_topic: odom
  map_frame: odom

  # Robot (diff drive)
  max_vel_x: 1.8
  max_vel_x_backwards: 0.4
  max_vel_theta: 0.7
  acc_lim_x: 1.5
  acc_lim_theta: 1.8

  # Footprint / safety
  footprint_model:
    type: "circular"
    radius: 0.50
  min_obstacle_dist: 0.45
  inflation_dist: 0.80

  # Goal tolerancie
  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.15
  free_goal_vel: false

  # Via-points

  # Optimalizácia
  teb_autosize: true
  dt_ref: 0.4
  dt_hysteresis: 0.1
  weight_obstacle: 120.0
  weight_viapoint: 0.0
  weight_kinematics_nh: 1000.0
  weight_kinematics_forward_drive: 1.0
  weight_optimaltime: 0.3
